name: course2016
channels:
   - conda-forge
dependencies:
   - python=3.5
   - ipython
   - jupyter
   - jpeg=9b
   - numpy
   - matplotlib
   - scipy
   - pandas
   - cartopy
   - basemap
   - iris=1.10
   - h5py
   - netcdf4
   - shapely
   - xarray
