name: course2016
channels:
   - conda-forge
dependencies:
   - python=3.5
   - ipython
   - jupyter
   - numpy
   - matplotlib
   - scipy
   - pandas
   - cartopy
   - basemap
   - netcdf4
   - shapely
   - xarray
   - iris=1.10
