name: course2016
channels:
   - conda-forge
   - scitools
dependencies:
   - python=3.5
   - ipython
   - jupyter
   - numpy
   - matplotlib
   - scipy
   - cartopy
   - basemap
   - iris
   - h5py
   - netcdf4
   - shapely
   - xarray
